from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path, PurePosixPath
from zipfile import ZIP_DEFLATED, ZipFile


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "dist" / "sage-aaai-code.zip"

EXCLUDED_PREFIXES = (
    ".git/",
    ".worktrees/",
    "build/",
    "dist/",
    "outputs/",
    "results/",
    "runs/",
    "data/raw/",
    "data/cache/",
    "data/generated/",
    "SkillOpt/outputs/",
    "SkillOpt/index.html",
    "SkillOpt/skillopt.html",
    "SkillOpt/skillopt-assets/",
    "SkillOpt/docs/",
    "SkillOpt/mkdocs.yml",
    "SkillOpt/CONTRIBUTING.md",
)

EXCLUDED_NAMES = {
    ".pytest_cache",
    "__pycache__",
}

OVERLAYS = {
    "SkillOpt/README.md": """# Vendored SkillOpt Runtime

This directory contains the SkillOpt runtime used by the anonymous SAGE
reproduction package. It is included so reviewers can run the baseline gate and
the SAGE-integrated gate from the same code appendix.

Install and smoke-check:

```bash
python -m pip install -e .
python -c \"import skillopt.engine.trainer\"
```

Run with SAGE:

```bash
python scripts/train.py --config configs/searchqa/default.yaml --gate_select sage
```
""",
    "SkillOpt/pyproject.toml": """[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "skillopt"
version = "0.1.0"
description = "Vendored SkillOpt runtime for anonymous SAGE reproduction"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
authors = [
    {name = "Anonymous Authors"},
]
keywords = ["agent", "prompt-optimization", "skill-learning", "LLM", "agentic"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "openai>=1.30.0",
    "pyyaml>=6.0",
    "numpy>=1.24.0",
    "openpyxl>=3.1.0",
    "azure-identity>=1.15.0",
    "azure-core>=1.30.0",
    "httpx>=0.27.0",
]

[project.optional-dependencies]
alfworld = ["alfworld>=0.4.0", "gymnasium>=0.29.0"]
claude = ["claude-agent-sdk>=0.1.0"]
qwen = ["vllm>=0.4.0"]
webui = ["gradio>=4.0.0"]
dev = ["ruff>=0.4.0", "pytest>=8.0.0"]
all = [
    "alfworld>=0.4.0",
    "gymnasium>=0.29.0",
    "claude-agent-sdk>=0.1.0",
]

[project.scripts]
skillopt-train = "scripts.train:main"
skillopt-eval = "scripts.eval_only:main"

[tool.setuptools.packages.find]
include = ["skillopt*", "scripts*", "sage*"]

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = ["E501"]
""",
    "SkillOpt/ckpt/README.md": """# Reference Skill Documents

This folder contains plain Markdown skill documents used by the vendored
runtime. They are included as code-like process artifacts, not as measured run
outputs. Use `scripts/train.py` to optimize a new skill from a benchmark
configuration.
""",
}


def _tracked_files() -> list[str]:
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=REPO_ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def _excluded(path: str) -> bool:
    posix = PurePosixPath(path)
    if any(part in EXCLUDED_NAMES or part.endswith(".egg-info") for part in posix.parts):
        return True
    return any(path == prefix.rstrip("/") or path.startswith(prefix) for prefix in EXCLUDED_PREFIXES)


def build_zip(output: Path, dry_run: bool = False) -> dict[str, list[str]]:
    included: list[str] = []
    excluded: list[str] = []
    files = _tracked_files()

    if dry_run:
        for rel in files:
            (excluded if _excluded(rel) else included).append(rel)
        return {"included": included, "excluded": excluded, "overlays": sorted(OVERLAYS)}

    output.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(output, "w", ZIP_DEFLATED) as archive:
        for rel in files:
            if _excluded(rel):
                excluded.append(rel)
                continue
            included.append(rel)
            if rel in OVERLAYS:
                archive.writestr(rel, OVERLAYS[rel])
            else:
                archive.write(REPO_ROOT / rel, rel)

        archive.writestr(
            "README_AAAI_APPENDIX.md",
            "This ZIP was generated by scripts/make_aaai_supplement.py from tracked files. "
            "It excludes local caches, outputs, raw data, and nonessential public web pages.\n",
        )

    return {"included": included, "excluded": excluded, "overlays": sorted(OVERLAYS)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Create an AAAI blind-review code appendix ZIP.")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    manifest = build_zip(args.out, dry_run=args.dry_run)
    print(json.dumps(manifest, indent=2, sort_keys=True))
    if not args.dry_run:
        print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
